import { MacroDashboard, Module, Factor, TrendPoint } from '@/types'

// Helper: generate trend data for a module over 30 days
function genTrend(base: number, volatility: number, days = 30): TrendPoint[] {
  const now = new Date('2026-02-25')
  const points: TrendPoint[] = []
  let val = base - volatility * 2
  for (let i = days; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    val = val + (Math.random() - 0.45) * volatility
    val = Math.max(0, Math.min(100, val))
    const label = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
    points.push({ date: label, value: parseFloat(val.toFixed(1)) })
  }
  // Nudge last point to match current score
  points[points.length - 1].value = base
  return points
}

// Helper: generate factor trend data (raw values, not 0-100)
function genFactorTrend(base: number, volatility: number, days = 90): TrendPoint[] {
  const now = new Date('2026-02-25')
  const points: TrendPoint[] = []
  let val = base
  for (let i = days; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    val = val + (Math.random() - 0.5) * volatility
    const label = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
    points.push({ date: label, value: parseFloat(val.toFixed(4)) })
  }
  return points
}

// Helper: generate percentile distribution histogram
function genPercentileDist(currentPct: number): { range: string; freq: number }[] {
  const buckets = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90', '90-100']
  return buckets.map((range, i) => {
    const center = i * 10 + 5
    const dist = Math.abs(center - currentPct)
    const freq = Math.max(2, Math.round(20 - dist * 0.3 + Math.random() * 5))
    return { range, freq }
  })
}

// ─── LIQUIDITY MODULE ────────────────────────────────────────────────────────

const liquidityFactors: Factor[] = [
  {
    id: 'fed-net-liquidity',
    name: 'Fed Net Liquidity',
    value: '$5.70T',
    sevenDayChange: '−0.00%',
    changeDirection: 'flat',
    historicalPercentile5Y: 28,
    status: 'restrictive',
    velocity: 'falling',
    trendData: genFactorTrend(5.7, 0.02),
    percentileData: genPercentileDist(28),
    isExtra: false,
  },
  {
    id: 'bank-reserves',
    name: 'Bank Reserves',
    value: '$2.95T',
    sevenDayChange: '−+0.00%',
    changeDirection: 'flat',
    historicalPercentile5Y: 55,
    status: 'restrictive',
    velocity: 'flat',
    trendData: genFactorTrend(2.95, 0.03),
    percentileData: genPercentileDist(55),
    isExtra: false,
  },
  {
    id: 'net-liquidity-momentum',
    name: 'Net Liquidity Momentum (13W)',
    value: '$52.94B',
    sevenDayChange: '↘ −34.64 pts',
    changeDirection: 'down',
    historicalPercentile5Y: 42,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(52.94, 5),
    percentileData: genPercentileDist(42),
    isExtra: false,
  },
  {
    id: 'tga-deviation',
    name: 'TGA Deviation',
    value: '$310.65B',
    sevenDayChange: '− 0.00 pts',
    changeDirection: 'flat',
    historicalPercentile5Y: 72,
    status: 'restrictive',
    velocity: 'flat',
    trendData: genFactorTrend(310.65, 15),
    percentileData: genPercentileDist(72),
    isExtra: false,
  },
  {
    id: 'on-rrp-buffer-risk',
    name: 'ON RRP Buffer Risk',
    value: '0.9817',
    sevenDayChange: '↘ −0.12%',
    changeDirection: 'down',
    historicalPercentile5Y: 88,
    status: 'restrictive',
    velocity: 'rising',
    trendData: genFactorTrend(0.9817, 0.02),
    percentileData: genPercentileDist(88),
    isExtra: false,
  },
  // Extra factors
  {
    id: 'fed-total-assets',
    name: 'Fed Total Assets',
    value: '$6.61T',
    sevenDayChange: '− +0.00%',
    changeDirection: 'flat',
    historicalPercentile5Y: 62,
    status: 'neutral',
    velocity: 'flat',
    trendData: genFactorTrend(6.61, 0.05),
    percentileData: genPercentileDist(62),
    isExtra: true,
  },
  {
    id: 'treasury-general-account',
    name: 'Treasury General Account',
    value: '$912.73B',
    sevenDayChange: '− +0.00%',
    changeDirection: 'flat',
    historicalPercentile5Y: 70,
    status: 'neutral',
    velocity: 'flat',
    trendData: genFactorTrend(912.73, 30),
    percentileData: genPercentileDist(70),
    isExtra: true,
  },
  {
    id: 'on-rrp',
    name: 'ON RRP',
    value: '$917.00M',
    sevenDayChange: '↗ +7.13%',
    changeDirection: 'up',
    historicalPercentile5Y: 15,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(0.917, 0.1),
    percentileData: genPercentileDist(15),
    isExtra: true,
  },
]

// ─── FUNDING MODULE ───────────────────────────────────────────────────────────

const fundingFactors: Factor[] = [
  {
    id: 'collateral-repo-friction',
    name: 'Collateral/Repo Friction',
    value: '0.03%',
    sevenDayChange: '↘ −6 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 45,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(0.03, 0.005),
    percentileData: genPercentileDist(45),
    isExtra: false,
  },
  {
    id: 'corridor-friction-1',
    name: 'Corridor Friction 1',
    value: '0.01%',
    sevenDayChange: '↘ −7 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 38,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(0.01, 0.003),
    percentileData: genPercentileDist(38),
    isExtra: false,
  },
  {
    id: 'corridor-friction-2',
    name: 'Corridor Friction 2',
    value: '0.16%',
    sevenDayChange: '↘ −7 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 52,
    status: 'restrictive',
    velocity: 'falling',
    trendData: genFactorTrend(0.16, 0.008),
    percentileData: genPercentileDist(52),
    isExtra: false,
  },
  {
    id: 'effr-iorb-spread',
    name: 'EFFR−IORB Spread',
    value: '−0.01%',
    sevenDayChange: '− +0 bps',
    changeDirection: 'flat',
    historicalPercentile5Y: 30,
    status: 'restrictive',
    velocity: 'flat',
    trendData: genFactorTrend(-0.01, 0.003),
    percentileData: genPercentileDist(30),
    isExtra: false,
  },
  {
    id: 'cp-tbill-spread',
    name: 'CP-TBill Spread',
    value: '0.06%',
    sevenDayChange: '↗ +1 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 25,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(0.06, 0.005),
    percentileData: genPercentileDist(25),
    isExtra: false,
  },
  {
    id: 'funding-fragmentation',
    name: 'Funding Fragmentation (21D)',
    value: '0.1046',
    sevenDayChange: '↗ +0.0121 pts',
    changeDirection: 'up',
    historicalPercentile5Y: 33,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(0.1046, 0.01),
    percentileData: genPercentileDist(33),
    isExtra: false,
  },
  // Extra factors
  {
    id: 'effr',
    name: 'EFFR',
    value: '3.64%',
    sevenDayChange: '− +0 bps',
    changeDirection: 'flat',
    historicalPercentile5Y: 60,
    status: 'neutral',
    velocity: 'flat',
    trendData: genFactorTrend(3.64, 0.05),
    percentileData: genPercentileDist(60),
    isExtra: true,
  },
  {
    id: 'sofr',
    name: 'SOFR',
    value: '3.66%',
    sevenDayChange: '↘ −7 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 62,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(3.66, 0.05),
    percentileData: genPercentileDist(62),
    isExtra: true,
  },
  {
    id: 'iorb',
    name: 'IORB',
    value: '3.65%',
    sevenDayChange: '− +0 bps',
    changeDirection: 'flat',
    historicalPercentile5Y: 61,
    status: 'neutral',
    velocity: 'flat',
    trendData: genFactorTrend(3.65, 0.05),
    percentileData: genPercentileDist(61),
    isExtra: true,
  },
  {
    id: 'on-rrp-award-rate',
    name: 'ON RRP Award Rate',
    value: '3.50%',
    sevenDayChange: '− +0 bps',
    changeDirection: 'flat',
    historicalPercentile5Y: 58,
    status: 'neutral',
    velocity: 'flat',
    trendData: genFactorTrend(3.50, 0.05),
    percentileData: genPercentileDist(58),
    isExtra: true,
  },
  {
    id: 'obfr-rate',
    name: 'OBFR Rate',
    value: '3.63%',
    sevenDayChange: '↘ −1 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 59,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(3.63, 0.05),
    percentileData: genPercentileDist(59),
    isExtra: true,
  },
  {
    id: 'srf-usage',
    name: 'SRF Usage',
    value: '$0.00M',
    sevenDayChange: '↘ −0.0020 pts',
    changeDirection: 'down',
    historicalPercentile5Y: 5,
    status: 'supportive',
    velocity: 'flat',
    trendData: genFactorTrend(0, 0.001),
    percentileData: genPercentileDist(5),
    isExtra: true,
  },
]

// ─── TREASURY MODULE ──────────────────────────────────────────────────────────

const treasuryFactors: Factor[] = [
  {
    id: '30y-10y-term-premium',
    name: '30Y-10Y Term Premium',
    value: '0.67%',
    sevenDayChange: '↗ +5 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 68,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(0.67, 0.05),
    percentileData: genPercentileDist(68),
    isExtra: false,
  },
  {
    id: '10y-rate-volatility',
    name: '10Y Rate Volatility (21D)',
    value: '0.0870',
    sevenDayChange: '↗ +0.0097 pts',
    changeDirection: 'up',
    historicalPercentile5Y: 55,
    status: 'neutral',
    velocity: 'rising',
    trendData: genFactorTrend(0.087, 0.008),
    percentileData: genPercentileDist(55),
    isExtra: false,
  },
  {
    id: 'curve-curvature',
    name: 'Curve Curvature (Abs)',
    value: '0.07%',
    sevenDayChange: '↗ +7 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 72,
    status: 'restrictive',
    velocity: 'rising',
    trendData: genFactorTrend(0.07, 0.005),
    percentileData: genPercentileDist(72),
    isExtra: false,
  },
  // Extra factors
  {
    id: '10y-2y-spread',
    name: '10Y-2Y Spread',
    value: '0.60%',
    sevenDayChange: '↘ −2 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 55,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(0.60, 0.03),
    percentileData: genPercentileDist(55),
    isExtra: true,
  },
  {
    id: '10y-3m-spread',
    name: '10Y-3M Spread',
    value: '0.34%',
    sevenDayChange: '↘ −5 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 48,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(0.34, 0.03),
    percentileData: genPercentileDist(48),
    isExtra: true,
  },
  {
    id: '10y-nominal-rate',
    name: '10Y Nominal Rate',
    value: '4.03%',
    sevenDayChange: '↘ −6 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 65,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(4.03, 0.08),
    percentileData: genPercentileDist(65),
    isExtra: true,
  },
  {
    id: '30y-rate',
    name: '30Y Rate',
    value: '4.70%',
    sevenDayChange: '↘ −1 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 70,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(4.70, 0.08),
    percentileData: genPercentileDist(70),
    isExtra: true,
  },
  {
    id: '2y-rate',
    name: '2Y Rate',
    value: '3.43%',
    sevenDayChange: '↘ −4 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 58,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(3.43, 0.07),
    percentileData: genPercentileDist(58),
    isExtra: true,
  },
]

// ─── RATES MODULE ─────────────────────────────────────────────────────────────

const ratesFactors: Factor[] = [
  {
    id: 'real-rate-level',
    name: 'Real Rate Level',
    value: '1.42%',
    sevenDayChange: '↘ −4 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 48,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(1.42, 0.06),
    percentileData: genPercentileDist(48),
    isExtra: false,
  },
  {
    id: 'real-curve',
    name: 'Real Curve (10Y-5Y)',
    value: '0.58%',
    sevenDayChange: '↗ +1 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 72,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(0.58, 0.04),
    percentileData: genPercentileDist(72),
    isExtra: false,
  },
  {
    id: '10y-breakeven',
    name: '10Y Breakeven',
    value: '2.26%',
    sevenDayChange: '↘ −3 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 65,
    status: 'supportive',
    velocity: 'falling',
    trendData: genFactorTrend(2.26, 0.05),
    percentileData: genPercentileDist(65),
    isExtra: false,
  },
  // Extra factors
  {
    id: '5y-real-rate',
    name: '5Y Real Rate',
    value: '1.19%',
    sevenDayChange: '↘ −4 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 66,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(1.19, 0.06),
    percentileData: genPercentileDist(66),
    isExtra: true,
  },
  {
    id: '10y-real-rate',
    name: '10Y Real Rate',
    value: '1.77%',
    sevenDayChange: '↘ −3 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 68,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(1.77, 0.06),
    percentileData: genPercentileDist(68),
    isExtra: true,
  },
]

// ─── CREDIT MODULE ────────────────────────────────────────────────────────────

const creditFactors: Factor[] = [
  {
    id: 'nfci',
    name: 'NFCI',
    value: '−0.57',
    sevenDayChange: '− 0.00 pts',
    changeDirection: 'flat',
    historicalPercentile5Y: 22,
    status: 'supportive',
    velocity: 'flat',
    trendData: genFactorTrend(-0.57, 0.05),
    percentileData: genPercentileDist(22),
    isExtra: false,
  },
  {
    id: 'hy-credit',
    name: 'HY Credit',
    value: '0.64%',
    sevenDayChange: '↗ +5 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 38,
    status: 'neutral',
    velocity: 'rising',
    trendData: genFactorTrend(0.64, 0.03),
    percentileData: genPercentileDist(38),
    isExtra: false,
  },
  {
    id: 'ig-credit',
    name: 'IG Credit',
    value: '0.38%',
    sevenDayChange: '↘ −16 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 42,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(0.38, 0.02),
    percentileData: genPercentileDist(42),
    isExtra: false,
  },
  {
    id: 'regional-banks-spy',
    name: 'Regional Banks vs SPY',
    value: '8.98%',
    sevenDayChange: '↘ −475 bps',
    changeDirection: 'down',
    historicalPercentile5Y: 58,
    status: 'supportive',
    velocity: 'falling',
    trendData: genFactorTrend(8.98, 0.8),
    percentileData: genPercentileDist(58),
    isExtra: false,
  },
]

// ─── RISK MODULE ──────────────────────────────────────────────────────────────

const riskFactors: Factor[] = [
  {
    id: 'vix',
    name: 'VIX',
    value: '19.55',
    sevenDayChange: '↘ −0.36%',
    changeDirection: 'down',
    historicalPercentile5Y: 48,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(19.55, 1.5),
    percentileData: genPercentileDist(48),
    isExtra: false,
  },
  {
    id: 'vix-term-structure',
    name: 'VIX Term Structure',
    value: '0.9161',
    sevenDayChange: '↘ −0.0011 pts',
    changeDirection: 'down',
    historicalPercentile5Y: 32,
    status: 'restrictive',
    velocity: 'falling',
    trendData: genFactorTrend(0.9161, 0.02),
    percentileData: genPercentileDist(32),
    isExtra: false,
  },
  {
    id: 'risk-vs-safe',
    name: 'Risk vs Safe',
    value: '4.45%',
    sevenDayChange: '↗ +308 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 55,
    status: 'neutral',
    velocity: 'rising',
    trendData: genFactorTrend(4.45, 0.3),
    percentileData: genPercentileDist(55),
    isExtra: false,
  },
  {
    id: 'high-beta-preference',
    name: 'High-Beta Preference',
    value: '8.72%',
    sevenDayChange: '↗ +25 bps',
    changeDirection: 'up',
    historicalPercentile5Y: 62,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(8.72, 0.5),
    percentileData: genPercentileDist(62),
    isExtra: false,
  },
  // Extra
  {
    id: 'vix-3m',
    name: 'VIX 3M',
    value: '21.34',
    sevenDayChange: '↘ −0.23%',
    changeDirection: 'down',
    historicalPercentile5Y: 45,
    status: 'neutral',
    velocity: 'falling',
    trendData: genFactorTrend(21.34, 1.2),
    percentileData: genPercentileDist(45),
    isExtra: true,
  },
]

// ─── EXTERNAL MODULE ──────────────────────────────────────────────────────────

const externalFactors: Factor[] = [
  {
    id: 'dxy',
    name: 'US Dollar Index (DXY)',
    value: '97.70',
    sevenDayChange: '↗ +0.08%',
    changeDirection: 'up',
    historicalPercentile5Y: 28,
    status: 'supportive',
    velocity: 'rising',
    trendData: genFactorTrend(97.7, 0.8),
    percentileData: genPercentileDist(28),
    isExtra: false,
  },
  {
    id: 'fx-realized-volatility',
    name: 'FX Realized Volatility',
    value: '0.0563',
    sevenDayChange: '↘ −1.94%',
    changeDirection: 'down',
    historicalPercentile5Y: 35,
    status: 'supportive',
    velocity: 'falling',
    trendData: genFactorTrend(0.0563, 0.005),
    percentileData: genPercentileDist(35),
    isExtra: false,
  },
  {
    id: 'wti-oil',
    name: 'WTI Oil',
    value: '$65.86',
    sevenDayChange: '↗ +1.03%',
    changeDirection: 'up',
    historicalPercentile5Y: 42,
    status: 'restrictive',
    velocity: 'rising',
    trendData: genFactorTrend(65.86, 1.5),
    percentileData: genPercentileDist(42),
    isExtra: false,
  },
  {
    id: 'oil-volatility-deviation',
    name: 'Oil Volatility Deviation',
    value: '22.885',
    sevenDayChange: '↗ +7.230 pts',
    changeDirection: 'up',
    historicalPercentile5Y: 65,
    status: 'restrictive',
    velocity: 'rising',
    trendData: genFactorTrend(22.885, 2),
    percentileData: genPercentileDist(65),
    isExtra: false,
  },
  {
    id: 'natural-gas',
    name: 'Natural Gas',
    value: '$2.83',
    sevenDayChange: '↘ −6.01%',
    changeDirection: 'down',
    historicalPercentile5Y: 25,
    status: 'supportive',
    velocity: 'falling',
    trendData: genFactorTrend(2.83, 0.15),
    percentileData: genPercentileDist(25),
    isExtra: false,
  },
]

// ─── MODULES ──────────────────────────────────────────────────────────────────

export const modules: Module[] = [
  {
    slug: 'liquidity',
    name: 'Liquidity',
    score: 20.3,
    prevScore: 20.3,
    sevenDayChangePct: -5.48,
    trendDays: 2,
    trendDirection: 'declining',
    percentile5Y: 20,
    lastUpdated: '15h ago',
    color: '#ef4444',
    trendData: genTrend(20.3, 3),
    factors: liquidityFactors,
  },
  {
    slug: 'funding',
    name: 'Funding',
    score: 42.9,
    prevScore: 41.7,
    sevenDayChangePct: 14.47,
    trendDays: 5,
    trendDirection: 'improving',
    percentile5Y: 43,
    lastUpdated: '15h ago',
    color: '#f97316',
    trendData: genTrend(42.9, 8),
    factors: fundingFactors,
  },
  {
    slug: 'treasury',
    name: 'Treasury',
    score: 59.1,
    prevScore: 82.2,
    sevenDayChangePct: -28.99,
    trendDays: 2,
    trendDirection: 'declining',
    percentile5Y: 59,
    lastUpdated: '15h ago',
    color: '#f97316',
    trendData: genTrend(59.1, 12),
    factors: treasuryFactors,
  },
  {
    slug: 'rates',
    name: 'Rates',
    score: 70.5,
    prevScore: 67.4,
    sevenDayChangePct: 7.44,
    trendDays: 2,
    trendDirection: 'improving',
    percentile5Y: 71,
    lastUpdated: '15h ago',
    color: '#14b8a6',
    trendData: genTrend(70.5, 6),
    factors: ratesFactors,
  },
  {
    slug: 'credit',
    name: 'Credit',
    score: 74.8,
    prevScore: 74.8,
    sevenDayChangePct: -2.87,
    trendDays: 1,
    trendDirection: 'stable',
    percentile5Y: 72,
    lastUpdated: '15h ago',
    color: '#14b8a6',
    trendData: genTrend(74.8, 5),
    factors: creditFactors,
  },
  {
    slug: 'risk',
    name: 'Risk',
    score: 50.3,
    prevScore: 50.4,
    sevenDayChangePct: 8.77,
    trendDays: 2,
    trendDirection: 'declining',
    percentile5Y: 50,
    lastUpdated: '15h ago',
    color: '#f97316',
    trendData: genTrend(50.3, 15),
    factors: riskFactors,
  },
  {
    slug: 'external',
    name: 'External',
    score: 50.1,
    prevScore: 50.1,
    sevenDayChangePct: -12.10,
    trendDays: 1,
    trendDirection: 'stable',
    percentile5Y: 48,
    lastUpdated: '15h ago',
    color: '#f97316',
    trendData: genTrend(50.1, 6),
    factors: externalFactors,
  },
]

// ─── MAIN DASHBOARD ───────────────────────────────────────────────────────────

export const dashboardData: MacroDashboard = {
  score: 52.4,
  prevScore: 55.0,
  trendDays: 2,
  trendDirection: 'declining',
  percentile5Y: 57,
  lastUpdated: '6h ago',
  trendData: genTrend(52.4, 4),
  modules,
  scoreLift: [
    { name: 'Corridor Friction 1', pts: 1.3 },
    { name: 'Collateral/Repo Friction', pts: 0.7 },
    { name: 'Natural Gas', pts: 0.6 },
    { name: 'High-Beta Preference', pts: 0.5 },
    { name: 'Real Curve (10Y-5Y)', pts: 0.4 },
    { name: 'SRF Usage', pts: 0.3 },
    { name: 'CP-TBill Spread', pts: 0.2 },
    { name: 'DXY', pts: 0.2 },
    { name: 'FX Realized Volatility', pts: 0.2 },
    { name: '10Y Breakeven', pts: 0.1 },
    { name: 'NFCI', pts: 0.1 },
    { name: '30Y-10Y Term Premium', pts: 0.1 },
    { name: 'Funding Fragmentation (21D)', pts: 0.1 },
    { name: 'Regional Banks vs SPY', pts: 0.1 },
    { name: 'Risk vs Safe', pts: 0.1 },
  ],
  scoreDrag: [
    { name: 'Curve Curvature (Abs)', pts: -3.1 },
    { name: 'WTI Oil', pts: -1.5 },
    { name: '10Y Rate Volatility (21D)', pts: -0.5 },
    { name: 'ON RRP Buffer Risk', pts: -0.4 },
    { name: 'TGA Deviation', pts: -0.3 },
    { name: 'VIX Term Structure', pts: -0.2 },
    { name: 'EFFR−IORB Spread', pts: -0.2 },
    { name: 'Net Liquidity Momentum (13W)', pts: -0.1 },
    { name: 'Oil Volatility Deviation', pts: -0.1 },
  ],
}

export function getModuleBySlug(slug: string): Module | undefined {
  return modules.find((m) => m.slug === slug)
}

export function getScoreColor(score: number): string {
  if (score < 33) return '#ef4444'
  if (score < 66) return '#f97316'
  return '#14b8a6'
}

export function getStatusColor(status: string): string {
  if (status === 'supportive') return '#22c55e'
  if (status === 'neutral') return '#f97316'
  return '#ef4444'
}
